networks:
  infra:
services:
  csvserver:
   image: infracloudio/csvserver:latest
   container_name: csvserver
   volumes:
    - "./gencsv.sh:/src/gencsv.sh"
   hostname: csvserver
   environment:
    - "CSVSERVER_BORDER: Orange"
   networks:
    - infra
   command: bash -c "/src/gencsv.sh"
   ports:
    - "9393:9300"
  prometheus:
   image: prom/prometheus:v2.22.0
   restart: unless-stopped
   user: root
   volumes:
     - ./prometheus:/etc/prometheus/
     - ./prometheus_data:/prometheus
   command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
     - '--web.console.templates=/usr/share/prometheus/consoles'
   ports:
     - 9090:9090
   networks:
    - infra
   depends_on:
     - csvserver
